<script src="http://code.jquery.com/jquery-1.6.4.min.js"></script>
<script src="<?php echo $this->baseUrl(); ?>/js/main.js"></script>

<div style="margin-left:auto;margin-right: auto;width: 200px;">

    <form action="<?=$this->url($this->formAction);?>" method="post" id="CloseForm">
    <input type="submit" name="btnSe" id="btnSe" value="Close">

</form>
<input type="button" id="postCoords" value="Check-In" style="width: 200px;height: 100px;"/></div>